### PR TITLE
Create Dependencies.md

### PR DESCRIPTION
**Pull request by lite20**

### CODE REVIEW

**Comment by lite20** [comment]
I have no write access on this repo so you'll have to merge this for me, thanks!

**Comment by piranna** [comment]
I could be able to merge it, but I was thinking about being it a life file
not intended to be added to the docs because dependencies can change... I
always found the docs repo more book alike, what do you think?

**Comment by lite20** [comment]
I don't know really. I often look to docs as a place where I can grab information on what I'm working on. I'm not sure how helpful the dependencies list may be,   that's true. It's up to you.

**Comment by piranna** [comment]
> I don't know really. I often look to docs as a place where I can grab
information on what I'm working on.

I think we should remove pages from the wiki that are already on the docs
repo (except the dependencies tree, obviously).

> I'm not sure how helpful the dependencies list may be, that's true. It's
up to you.

It's not something introductory, but a programmers help. It could be added
a minimal version just with the own projects (not all the dependencies)
since this will mostly don't change too much with a link to the original
one, and maybe remove the badges...

**Pull request merged**
